export enum Cor {
  Amarelo = 'Amarelo',
  Azul = 'Azul',
  Bege = 'Bege',
  Branco = 'Branco',
  Cinza = 'Cinza',
  Dourado = 'Dourado',
  Laranja = 'Laranja',
  Marrom = 'Marrom',
  Nude = 'Nude',
  Preto = 'Preto',
  Prateado = 'Prateado',
  Rosa = 'Rosa',
  Roxo = 'Roxo',
  Transparente = 'Transparente',
  Verde = 'Verde',
  Vermelho = 'Vermelho',
  Vinho = 'Vinho',
  Outro = 'Outro',
}
